Task 1

In [1]:
import numpy as np
from sklearn.datasets import load_wine
wine = load_wine()

Task 2

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(wine['data'], wine['target'],random_state=2707)  
# split into train & test

In [3]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification

clf = MLPClassifier().fit(X_train, y_train)
#print(X_test)
clf.predict_proba(X_test[:])
clf.predict(X_test[:5, :])
clf.score(X_test, y_test)

0.4666666666666667

Task 3

In [4]:
from sklearn.model_selection import cross_val_score
mlp = MLPClassifier()
cross_val_score(clf, wine.data, wine.target)

/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


array([0.63888889, 0.33333333, 0.94444444, 0.62857143, 0.42857143])

Task 4

In [5]:
clf = MLPClassifier(max_iter=1240).fit(X_train, y_train)
cross_val_score(clf, wine.data, wine.target)

array([0.38888889, 0.97222222, 0.91666667, 0.34285714, 0.65714286])

Task 5

In [6]:
from sklearn.metrics import accuracy_score
clf5 = MLPClassifier(max_iter=1240)
clf5.fit(X_train, y_train)
y_pred = clf5.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
err = 1- accuracy
print("error: ", err)

error:  0.24444444444444446


Task 6:

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Normalizer

pipe = make_pipeline(Normalizer(), MLPClassifier(max_iter=2400))
pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

0.9555555555555556

In [9]:
# Various pre-processing steps
from sklearn.preprocessing import Normalizer, StandardScaler, MinMaxScaler, RobustScaler
from sklearn.model_selection import GridSearchCV

param_grid = {'normalizer': [MinMaxScaler(), Normalizer(), RobustScaler(), StandardScaler()],
              'mlpclassifier__alpha': [0.01, 0.1, 1, 10, 100]}
grid = GridSearchCV(pipe, param_grid=param_grid, n_jobs=-1, cv=5)
grid.fit(X_train, y_train)
grid.best_estimator_
print("Best cross-validation accuracy:", grid.best_score_)
print("Test set score:", grid.score(X_test, y_test))
print("Best parameters:", grid.best_params_)

Best cross-validation accuracy: 0.9925925925925926
Test set score: 0.9777777777777777
Best parameters: {'mlpclassifier__alpha': 0.1, 'normalizer': MinMaxScaler()}


Task 7:

In [11]:
y_pred = grid.predict(X_test)
accuracy_t7 = accuracy_score(y_test, y_pred)
err_t7 = 1- accuracy_t7
print("error: ", err_t7)

error:  0.022222222222222254


# USPS dataset

Task 1

In [12]:
import numpy
train_file = 'zip.train.gz'
test_file = 'zip.test.gz'
USPS_train_data = np.genfromtxt(train_file, dtype=str)
USPS_test_data = np.genfromtxt(test_file, dtype=str)

usps = np.append(USPS_train_data, USPS_test_data, axis=0)

Task 2

In [13]:
from sklearn.model_selection import train_test_split
usps_data = usps[:, 1:257]
usps_target = usps[:,0]
X_train_usps, X_test_usps, y_train_usps, y_test_usps = train_test_split(usps_data, usps_target,random_state=2707)  
# split into train & test

In [14]:
clf_usps = MLPClassifier().fit(X_train_usps, y_train_usps)
clf_usps.predict_proba(X_test_usps[:])
clf_usps.predict(X_test_usps[:5, :])
clf_usps.score(X_test_usps, y_test_usps)

/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
/Users/alpeshkumar/opt

0.6765591397849462

Task 3

In [15]:
mlp_usps = MLPClassifier()
cross_val_score(clf_usps, usps_data, usps_target)

/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is b

array([0.67526882, 0.65483871, 0.65913978, 0.68531469, 0.67832168])

Task 4

In [17]:
clf_usps = MLPClassifier(max_iter=1240).fit(X_train_usps, y_train_usps)
cross_val_score(clf_usps, usps_data, usps_target)

/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26).

array([0.65752688, 0.65537634, 0.67956989, 0.68961807, 0.67294244])

Task 5

In [18]:
clf_usps_5 = MLPClassifier(max_iter=1240)
clf_usps_5.fit(X_train_usps, y_train_usps)
y_pred_usps = clf_usps_5.predict(X_test_usps)
accuracy = accuracy_score(y_test_usps, y_pred_usps)
err_usps = 1- accuracy
print("error: ", err_usps)

error:  0.3290322580645161


/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)


Task 6:

In [20]:
pipe_usps = make_pipeline(Normalizer(), MLPClassifier(max_iter=2400))
pipe_usps.fit(X_train_usps, y_train_usps)
pipe_usps.score(X_test_usps, y_test_usps)

/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
/Users/alpeshkumar/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26).

0.6748387096774193

In [24]:
param_grid_usps = {'normalizer': [MinMaxScaler(), Normalizer(), RobustScaler(), StandardScaler()],
              'mlpclassifier__alpha': [0.01, 0.1, 1, 10, 100]}
grid_usps = GridSearchCV(pipe_usps, param_grid=param_grid_usps, n_jobs=-1, cv=5)
grid_usps.fit(X_train_usps, y_train_usps)
grid_usps.best_estimator_
print("Best cross-validation accuracy:", grid_usps.best_score_)
print("Test set score:", grid_usps.score(X_test_usps, y_test_usps))
print("Best parameters:", grid_usps.best_params_)

Best cross-validation accuracy: 0.7425782796727398
Test set score: 0.76
Best parameters: {'mlpclassifier__alpha': 1, 'normalizer': MinMaxScaler()}


Task 7

In [26]:
y_pred_usps = grid_usps.predict(X_test_usps)
accuracy_t7_usps = accuracy_score(y_test_usps, y_pred_usps)
err_t7_usps = 1- accuracy_t7_usps
print("error: ", err_t7_usps)

error:  0.24
